/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";
import { useGesture } from "react-use-gesture";
import { useSpring, a } from "@react-spring/three";
import { useThree } from "react-three-fiber";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF("/klaspic.glb");

	return (
		<group ref={group} {...props} dispose={null}>
			<group position={[-0.55, 3.61, -0.2]} scale={[0.7, 1, 0.4]}>
				<a.mesh {...spring} {...bind()}>
					<mesh
						material={materials.Material}
						geometry={nodes.Cube_1.geometry}
					/>
					<mesh material={materials.front} geometry={nodes.Cube_2.geometry} />
					<mesh
						material={materials["CC0Textures/Metal032/2K-JPG"]}
						geometry={nodes.Cube_3.geometry}
					/>
					{/* <mesh
					material={nodes.bool_obj.material}
					geometry={nodes.bool_obj.geometry}
					position={[0.87, -0.81, 0.61]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/> */}
				</a.mesh>
			</group>
		</group>
	);
}

useGLTF.preload("/klaspic.glb");
