/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: matov.potya2013 (https://sketchfab.com/matov.potya2013)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/router-wifi-0b823628757f416dbd1501dfd9ec683d
title: Router Wifi
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/scene.gltf');
	return (
		<group scale={[0.2, 0.2, 0.2]} position={[0, 0, 0]} ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[280.91, -3.34, -102.42]}>
						<mesh material={materials.material} geometry={nodes['Cube_3_����������������_0'].geometry} />
					</group>
					<group position={[53.79, -3.34, -102.42]}>
						<mesh material={materials.material} geometry={nodes['Cube_2_����������������_0'].geometry} />
					</group>
					<group position={[53.3, 99.32, -111.88]}>
						<mesh material={materials.material} geometry={nodes['Cone_2_����������������_0'].geometry} />
					</group>
					<group position={[280.76, 99.32, -111.88]}>
						<mesh material={materials.material} geometry={nodes['Cone_1_����������������_0'].geometry} />
					</group>
					<group position={[196.54, 32.79, 49.82]}>
						<mesh material={materials.material_2} geometry={nodes['Disc_1_����������������_0'].geometry} />
					</group>
					<group position={[153.8, 32.79, 49.82]}>
						<mesh material={materials.material_2} geometry={nodes['Disc_3_����������������_0'].geometry} />
					</group>
					<group position={[160.1, 32.79, 49.82]}>
						<mesh material={materials.material_2} geometry={nodes['Disc_2_����������������_0'].geometry} />
					</group>
					<group position={[141.54, 32.79, 49.82]}>
						<mesh material={materials.material_2} geometry={nodes['Disc_����������������_0'].geometry} />
					</group>
					<group position={[167.65, 0, 0]}>
						<mesh material={materials.material_3} geometry={nodes['Cube_����������������1_0'].geometry} />
					</group>
					<group position={[-4.07, -2.77, 1.52]}>
						<group position={[22.32, 34.92, 0]}>
							<mesh
								material={materials.NURBS_2__0}
								geometry={nodes['������������������������NURBS_2__0'].geometry}
							/>
						</group>
					</group>
					<group position={[167.65, 1.46, 9.64]}>
						<mesh material={materials.material} geometry={nodes['Cube_1_����������������_0'].geometry} />
						<mesh material={materials.material_3} geometry={nodes['Cube_1_����������������1_0'].geometry} />
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/scene.gltf');
