/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Sil(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/sil.glb');
	return (
		<group ref={group} {...props} dispose={null}>
			<group position={[0.01, 1.47, -0.12]} rotation={[-Math.PI, -0.08, -Math.PI]} scale={[0.47, 0.19, 0.47]}>
				<mesh
					material={nodes.F_Sm_highknob_bb_twistknownarrow_011.material}
					geometry={nodes.F_Sm_highknob_bb_twistknownarrow_011.geometry}
				/>
				<mesh material={materials['S Kevlar']} geometry={nodes.Cylinder072.geometry} />
				<mesh material={materials['S Plastic']} geometry={nodes.Cylinder072_1.geometry} />
				<mesh material={materials['S Chrome']} geometry={nodes.Cylinder072_2.geometry} />
			</group>
			<group position={[0, 0.97, 0]} scale={[0.14, 0.5, 0.36]}>
				<mesh material={materials.box} geometry={nodes.Cube001.geometry} />
				<mesh material={materials['Screw chrome']} geometry={nodes.Cube001_1.geometry} />
				<mesh material={materials['BNC White 001']} geometry={nodes.Cube001_2.geometry} />
				<mesh material={materials['Screw dark 001']} geometry={nodes.Cube001_3.geometry} />
				{/* <mesh
					material={nodes.bool_obj.material}
					geometry={nodes.bool_obj.geometry}
					position={[1, 0.32, -0.02]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={[2.79, 5.77, 2]}
				/>
				<mesh
					material={nodes.bool_obj001.material}
					geometry={nodes.bool_obj001.geometry}
					position={[-0.12, 0.09, -1]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={[5.77, 2.79, 2]}
				/>
				<mesh
					material={nodes.bool_obj002.material}
					geometry={nodes.bool_obj002.geometry}
					position={[0.03, 0.55, -1]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={[5.77, 2.79, 2]}
				/>
				<mesh
					material={nodes.bool_obj003.material}
					geometry={nodes.bool_obj003.geometry}
					position={[0.08, 0.54, -0.93]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={[5.77, 2.79, 2]}
				/>
				<mesh
					material={materials.usb}
					geometry={nodes.bool_obj004.geometry}
					position={[0.07, 0.54, -0.89]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={[5.77, 2.79, 2]}
				/> */}
				<mesh
					material={materials['CC0Textures/Metal029/1K-JPG']}
					geometry={nodes.Nut.geometry}
					position={[0.06, 0.77, -0.9]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={[0.05, 0.08, 0.01]}
				/>
				<mesh
					material={materials['CC0Textures/Metal029/1K-JPG']}
					geometry={nodes.Nut001.geometry}
					position={[0.06, 0.32, -0.9]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={[0.05, 0.08, 0.01]}
				/>
				<mesh
					material={materials.text}
					geometry={nodes.Text.geometry}
					position={[0.97, -0.24, 0.06]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={[0.34, 0.52, 0.25]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/sil.glb');
