/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/silvusafterchrome.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.47, 1.41, -0.68]} scale={[0.27, 1.11, 0.59]}>
        <mesh material={materials.Material} geometry={nodes.Cube_1.geometry} />
        <mesh material={materials['CC0Textures/Metal027/1K-JPG']} geometry={nodes.Cube_2.geometry} />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj.geometry}
          position={[0.01, 0.52, -1]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj001.geometry}
          position={[0.02, 0.53, -1.04]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          material={nodes.bool_obj002.material}
          geometry={nodes.bool_obj002.geometry}
          position={[-0.01, 0.54, -0.95]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj003.geometry}
          position={[0.01, 0.79, -1.04]}
          rotation={[1.57, 0, -Math.PI]}
        />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj004.geometry}
          position={[-0.02, 0.27, -1.04]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj005.geometry}
          position={[1, 0.28, 0.01]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          material={materials['CC0Textures/Metal027/1K-JPG']}
          geometry={nodes.bool_obj006.geometry}
          position={[0.02, 0.87, -1]}
          rotation={[1.66, 0, -Math.PI]}
          scale={[3.74, 1.69, 0.91]}
        />
        <group position={[0.02, 2.83, 0.62]} scale={[1.23, 0.64, 0.44]}>
          <mesh material={materials['CC0Textures/Plastic006/1K-JPG']} geometry={nodes.Cylinder_1.geometry} />
          <mesh material={materials['CC0Textures/Metal012/1K-JPG']} geometry={nodes.Cylinder_2.geometry} />
          <mesh material={materials['CC0Textures/Plastic006/1K-JPG']} geometry={nodes.CylinderPlate.geometry} />
        </group>
        <group position={[-0.06, 2.83, -0.64]} scale={[1.23, 0.64, 0.44]}>
          <mesh material={materials['CC0Textures/Plastic006/1K-JPG']} geometry={nodes.Cylinder002_1.geometry} />
          <mesh material={materials['CC0Textures/Metal012/1K-JPG']} geometry={nodes.Cylinder002_2.geometry} />
          <mesh material={materials['CC0Textures/Plastic006/1K-JPG']} geometry={nodes.Cylinder001Plate.geometry} />
        </group>
        <mesh
          material={materials['.Examples_033']}
          geometry={nodes.Examples_033.geometry}
          position={[-0.04, 0.27, -1.13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.25, 0.45, 0.33]}
        />
        <mesh
          material={materials['.Examples_033']}
          geometry={nodes.Examples_033001.geometry}
          position={[-0.01, 0.79, -1.12]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.25, 0.45, 0.33]}
        />
      </group>
      <mesh
        material={materials['CC0Textures/Metal029/1K-JPG']}
        geometry={nodes.Text.geometry}
        position={[-0.21, 1.04, -0.7]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.17, 0.17, 0.17]}
      />
      <mesh
        material={materials['CC0Textures/Metal027/1K-JPG']}
        geometry={nodes.Cylinder002.geometry}
        position={[-0.46, 2.64, -0.78]}
        scale={[-0.26, -0.26, -0.26]}>
        <mesh
          material={materials['CC0Textures/Metal012/1K-JPG.001']}
          geometry={nodes.Nut.geometry}
          position={[0.05, 0.34, 0.01]}
          scale={[0.09, 0.09, 0.09]}
        />
      </mesh>
      <group position={[-0.46, 2.56, -0.55]} scale={[0.2, 0.16, 0.2]}>
        <mesh material={materials['CC0Textures/Metal027/1K-JPG']} geometry={nodes.Cylinder001.geometry} />
        <mesh material={materials['Material.002']} geometry={nodes.Cylinder001_1.geometry} />
      </group>
      <mesh
        material={materials['CC0Textures/Metal012/1K-JPG.001']}
        geometry={nodes.Bolt.geometry}
        position={[-0.48, 2.49, -0.94]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['CC0Textures/Metal012/1K-JPG.001']}
        geometry={nodes.Bolt001.geometry}
        position={[-0.49, 2.49, -1.16]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['CC0Textures/Metal012/1K-JPG.001']}
        geometry={nodes.Bolt002.geometry}
        position={[-0.46, 2.49, -0.21]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['CC0Textures/Metal012/1K-JPG.001']}
        geometry={nodes.Bolt003.geometry}
        position={[-0.46, 2.5, -0.42]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/silvusafterchrome.glb')
